version: '3.3'

services:
  web:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ../:/workspace
      - ./config/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    build: ./php-mysql
    image: php-mysql
    ports:
      - 9000:9000
    volumes:
      - ../:/workspace
    links:
    - db
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - ./config/db-dump:/docker-entrypoint-initdb.d
      - ../database:/var/lib/mysql
    env_file: ./config/mysql.env